" Setup vim package manager
set nocompatible
call plug#begin()
Plug 'sheerun/vim-polyglot'
call plug#end()

" Setup main visual outlook
set cursorline
set display=lastline
set hidden
set hlsearch
set incsearch
set laststatus=2
set number
set report=0
set showcmd
set showmode
set splitbelow
set splitright
set synmaxcol=200
set wrapscan

" Setup interface behaviour
set autoindent
set backspace=indent,eol,start
set expandtab
set mouse=a
set shiftround
set shiftwidth=2
set softtabstop=2

" Setup temp file locations
set backup
set backupdir=$HOME/.vim/files/back//
set directory=$HOME/.vim/files/swap//
set swapfile
set undodir=$HOME/.vim/files/undo//
set undofile
set updatecount=100
set updatetime=2000

" Setup external shell prog
set shell=/bin/bash

" Setup line numbers color
highlight LineNr ctermfg=244
